### ISSUE TITLE
Issue loading neotoma2 through devtools

### ISSUE THREAD

**Issue by jessicablois** [NeotomaDB/neotoma2#1]
I am getting the following error when trying to load neotoma2:

Error in makePrototypeFromClassDef(properties, ClassDef, immediate, where) : 
  in making the prototype for class “publication” elements of the prototype failed to match the corresponding slot class: author (class "contacts" )
Error: unable to load R code in package ‘neotoma2’
Execution halted

**Comment by meghalithic** [comment]
I am getting a similar error when running devtools::install_github('NeotomaDB/neotoma2'). Here is the error message:

Error: Failed to install 'unknown package' from GitHub:
HTTP error 404.
No commit found for the ref master
Did you spell the repo owner (`NeotomaDB`) and repo name (`neotoma2`) correctly?
If spelling is correct, check that you have the required permissions to access the repo.

**Comment by jessicablois** [comment]
Hmmm, I was just able to load it from github, though I had to add “force=T”. Could you try again? Maybe there was a little blip in the GitHub repo?

devtools::install_github('NeotomaDB/neotoma2', force=TRUE)


Best,
Jessica

------------------------------------------
Associate Professor
School of Natural Sciences
University of California, Merced

Faculty Director
UC Merced Natural Reserve System
Office: SE1 296
Phone: (209) 228-2256
Email: ***@***.***
Web: http://jessicablois.com
Pronouns: She/Her/Hers


From: Meghan Balk ***@***.***>
Reply-To: NeotomaDB/neotoma2 ***@***.***>
Date: Wednesday, June 9, 2021 at 10:34 AM
To: NeotomaDB/neotoma2 ***@***.***>
Cc: Jessica Blois ***@***.***>, Author ***@***.***>
Subject: Re: [NeotomaDB/neotoma2] Issue loading neotoma2 through devtools (#1)


I am getting a similar error when running devtools::install_github('NeotomaDB/neotoma2'). Here is the error message:

Error: Failed to install 'unknown package' from GitHub:
HTTP error 404.
No commit found for the ref master

Did you spell the repo owner (NeotomaDB) and repo name (neotoma2) correctly?

  *   If spelling is correct, check that you have the required permissions to access the repo.

**Comment by meghalithic** [comment]
I was able to fix it by updating R from 4.0 to 4.1 and re-installing the package devtools. I also did "force = TRUE" and said no to updating files/packages that need compilation.
Oddly, though, @c-tome had no problem and is using R version 3.6.

**Comment by jessicablois** [comment]
Hmmm, odd. I’m using R4.0.4. But glad it’s working now! Note that this is still a beta version of the package and so some functionality may not be working appropriately!

Best,
Jessica

------------------------------------------
Associate Professor
School of Natural Sciences
University of California, Merced

Faculty Director
UC Merced Natural Reserve System
Office: SE1 296
Phone: (209) 228-2256
Email: ***@***.***
Web: http://jessicablois.com
Pronouns: She/Her/Hers


From: Meghan Balk ***@***.***>
Reply-To: NeotomaDB/neotoma2 ***@***.***>
Date: Wednesday, June 9, 2021 at 10:48 AM
To: NeotomaDB/neotoma2 ***@***.***>
Cc: Jessica Blois ***@***.***>, Author ***@***.***>
Subject: Re: [NeotomaDB/neotoma2] Issue loading neotoma2 through devtools (#1)


I was able to fix it by updating R from 4.0 to 4.1 and re-installing the package devtools.
Oddly, though, @c-tome<https://github.com/c-tome> had no problem and is using R version 3.6.

**Comment by SimonGoring** [comment]
This is all sorted now.  Closing the issue.
