### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by amy-mcg** [NeotomaDB/neotoma2#23]
I'm having trouble installing via devtools. I'm using `devtools::install_github("NeotomaDB/neotoma2", force = TRUE)` however getting the below error:

```
* installing *source* package ‘neotoma2’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in charToDate(x) : 
  character string is not in a standard unambiguous format
Error: unable to load R code in package ‘neotoma2’
Execution halted
ERROR: lazy loading failed for package ‘neotoma2’
```

Config info:

$platform
[1] "x86_64-apple-darwin15.6.0"

$os
[1] "darwin15.6.0"

$system
[1] "x86_64, darwin15.6.0"

$version.string
[1] "R version 3.6.1 (2019-07-05)"

**Comment by sedv8808** [comment]
Hi, we are on CRAN already, could you do:
```
install.packages('neotoma2')
```
?
