### ISSUE TITLE
neotoma R package filters out sites with no apparent reason

### ISSUE THREAD

**Issue by jamoschla** [NeotomaDB/neotoma2#25]
I am currently trying to download bulks of data with the neotoma R package. For example all pollen data available. The explorer indicates 4000+ available datasets, also: get_sites(datasettype= "pollen", all_data=TRUE) results in the same number.  

Only as soon as i use get_datasets or get_downloads the number of datasets is reduced drastically, leaving me with as little as 900 remaining. 

Any Ideas what the problem could be and how it can be fixed?

Thanks

**Comment by SimonGoring** [comment]
Thanks for reporting this. Could you share a small code example just so I can test it out?

**Comment by jamoschla** [comment]
Thanks for the quick reply. 

library(neotoma2)


x<- get_sites(datasettype="pollen", all_data=TRUE) 
results in 5039 Elements

y<- get_datasets(x, all_data=TRUE)
results in 2589 Elements

z<- neotoma2::get_downloads(y)
results in 1389 Elements

Thank you

**Comment by sedv8808** [comment]
Hello, can you do `install.packages('neotoma2')`

This issue should have been solved :)

However: Please try to filter your data before doing a big `get_downloads()` - A big pull of information might take a long time.
