### ISSUE TITLE
JOSS review: documentation does not include vignettes. These should be produced using pkgdown

### ISSUE THREAD

**Issue by kanishkan91** [NeotomaDB/neotoma2#30]
The current docs- http://open.neotomadb.org/neotoma2/ dont include the vignettes. I think the authors would just have to do 

`pkgdown::build_articles()` to generate these and include them on the GitHub docs. 

https://github.com/openjournals/joss-reviews/issues/5561

**Comment by SimonGoring** [comment]
Thank you for this suggestion. I have added the change (in develop currently). Will be merging shortly.
