### ISSUE TITLE
JOSS review: Add a summary of current available sites that can be queried

### ISSUE THREAD

**Issue by kanishkan91** [NeotomaDB/neotoma2#34]
Given this is a live package where users can add sites etc, can the authors report the total available sites that can be queried by this package? Ideally there should be a function that just reports this. Authors can also add this to a table in the README.

https://github.com/openjournals/joss-reviews/issues/5561

**Comment by sedv8808** [comment]
get_stats() function has been created

**Comment by kanishkan91** [comment]
@sedv8808 Could you add a line in the documentation for this new function? Just what it does and how it can be used
