### ISSUE TITLE
JOSS review (optional): Add link to rendered vignettes to docs

### ISSUE THREAD

**Issue by mhesselbarth** [NeotomaDB/neotoma2#36]
It would be nice if the link in the `README` provides a rendered HTML vignette directly. Maybe using Articles ([more information here](https://r-pkgs.org/vignettes.html)) would be nice. However, not necessarily required, just a suggestion.

https://github.com/openjournals/joss-reviews/issues/5561

**Comment by sedv8808** [comment]
Commit 199e3d5 addresses this issue
