### ISSUE TITLE
JOSS Review: Code of conduct

### ISSUE THREAD

**Issue by mhesselbarth** [NeotomaDB/neotoma2#39]
Refer to code of conduct guidelines in documentation (Suggestions: Somewhere in the *Tips for Contributing* section)

https://github.com/openjournals/joss-reviews/issues/5561

**Comment by SimonGoring** [comment]
Hi @mhesselbarth, we can certainly add a link to (or reference) the JOSS Code of Conduct. There is already a [code of conduct] for the repo, that both covers the JOSS one (I believe) and goes a bit further. Is the point you're making to ensure that the Code is referenced within the vignettes/documentation itself? Or just in the README?

Thanks!

**Comment by mhesselbarth** [comment]
Hey, 

Yes, its great you already have a Code of Conduct document. I think just adding one sentence in the "Tips for Contributing" section would be sufficient. Something along the lines of "If you want to contribute to this project, please be aware of our [Code of Conduct](https://github.com/NeotomaDB/neotoma2/blob/production/CODE_OF_CONDUCT.md)".
