### ISSUE TITLE
Preferred citation for neotoma2

### ISSUE THREAD

**Issue by Rekyt** [NeotomaDB/neotoma2#4]
Hello `neotoma2` developers 👋 
I'd like to reference `neotoma2` in an academic paper.
What's the preferred citation in this case?
I've used the default `citation("neotoma2")` citation generated by R:
```
@Manual{,
    title = {neotoma2: Working with the Neotoma Paleoecology Database},
    author = {Simon Goring},
    year = {2021},
    note = {R package version 0.0.0.9000},
  }
```

Is this ok?
You could override this behavior by having an explicit `CITATION` file in the `inst/` folder.

Many thanks!

**Comment by SimonGoring** [comment]
I have updated the citation for the package, and we hope to have a more extensive citation following publication of the package.
